name: PR run tests

on: 
  pull_request:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          PATH="${PATH}:${HOME}/.local/bin" && export PATH
          poetry config virtualenvs.create false && poetry install --with dev
      - name: Run tests
        run: python -m pytest -n auto

